services:
 catalogdb:
  image: postgres
  networks:
    - app_network
 basketdb:
  image: postgres
  networks:
    - app_network
 distributedcache:
  image: redis
  networks:
    - app_network
 pgadmin:
  image: dpage/pgadmin4

 catalog.api:
   image: ${DOCKER_REGISTRY-}catalogapi
   build:
     context: .
     dockerfile: Services/Catalog/Catalog.API/Dockerfile
   networks:
    - app_network
 basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile
    networks:
    - app_network
 discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile
    networks:
    - app_network

volumes:
  postgres_catalog:
  postgres_basket:
  pgadmin_admin:
  container_name:

networks:
  app_network:
   driver: bridge


