services:
 catalogdb:
  image: postgres
 pgadmin:
  image: dpage/pgadmin4

volumes:
  postgres_catalog:
  pgadmin_admin:


  # catalog.api:
  #   image: ${DOCKER_REGISTRY-}catalogapi
  #   build:
  #     context: .
  #     dockerfile: Services/Catalog/Catalog.API/Dockerfile
