services:
  catalogdb:
   container_name: catalogDB
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=catalogdb
   restart: always
   ports:
       - "5432:5432"
   volumes:
       - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
   container_name: basketdb
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=basketdb
   restart: always
   ports:
       - "5433:5432"
   volumes:
       - postgres_basket:/var/lib/postgresql/data/

  orderdb:
   container_name: orderdb
   environment:
    - ACCEPT_EULA=Y
    - SA_PASSWORD=SampleTest123 
   restart: always
   ports:
       - "1433:1433"
   volumes:
       - sql_orderdb:/var/lib/sql/data/

  distributedcache:
   container_name: distributedcache
   restart: always
   ports:
       - "6379:6379"
   volumes:
       - container_name:/var/lib/postgresql/data/

  pgadmin:
   container_name: pgadmin
   environment:
    - PGADMIN_DEFAULT_EMAIL=epuri.yeshu@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=test2345
   restart: always
   ports:
       - "15080:80"
   volumes:
       - pgadmin_admin:/var/lib/pgadmin_admin/data/


  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Database=catalogdb;Port=5432;User Id=postgres;Password=postgres
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  basket.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Database=basketdb;Port=5432;User Id=postgres;Password=postgres
      - ConnectionStrings__Redis=distributedcache:6379
      - GrpcSettings__DiscountUrl=https://discount.grpc:8081
    depends_on:
      - basketdb
      - distributedcache
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  discount.grpc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=discountdb
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
